### PR TITLE
feat(dimmableLight): 💡 added support for dimmable lights

### PR DESCRIPTION
**Pull request by CedricGatay**
* dimmable lights exposed through Tahoma API are now manageable
* wink effect at full brightness is implemented
* scan interval of 30s
* brightness is mapped from percentages to/from 8 bit scale
* there is no support for timed on / off as it is better done with an automation in my POV

### CODE REVIEW

**Comment by vlebourl** [comment]
thanks

**Comment by iMicknl** [comment]
Thanks! I was just looking into building this myself, will try your implementation tomorrow. :)

**Comment by iMicknl** [comment]
@CedricGatay will you work on merging this change into home assistant core?

**Comment by CedricGatay** [comment]
I was wondering if it should be done and why the work that @vlebourl did here is not merged ?

**Comment by iMicknl** [comment]
@cedricgatay I was wondering the same. I guess they still accept changes to the Tahoma component?

**Comment by vlebourl** [comment]
To be fair, this repo was just for my personal use at first, but I'm happy people are taking interest. Now, as the code does not fit in anyway the standards for submission into home assistant core, I use it as a draft for testing. Some features have been merged into the core, such as the smart lock (removed from release 0.5). But it take quite some time to clean up the code and submit it to HA, so I haven't done it for other features so far...

**Pull request merged**
